format_version: v1.0
type: UniqueComponent
attributes: {id: BSP_PIC32CX_WBZ451_Curiosity, bsp: 'true'}
children:
- type: ElementPosition
  attributes: {x: '30', y: '340', id: BSP_PIC32CX_WBZ451_Curiosity}
